export const rows = [
    {
        name: "PCR Test",
        name2: "PCR Test",
        date: "Feb 15, 2020",
        payment: "**** 4231",
        fees: "$3,500",
        status: "Scheduled",
    },
    {
        name: "Antigen Test",
        name2: "Antigen Test",
        date: "Feb 15, 2020",
        payment: "**** 4231",
        fees: "$1,800",
        status: "Postponed",
    },
    {
        name: "Diopter check",
        name2: "Diopter check",
        date: "Feb 15, 2020",
        payment: "**** 4231",
        fees: "$4,500",
        status: "Scheduled",
    },
    {
        name: "Diopter check",
        name2: "Diopter check",
        date: "Feb 15, 2020",
        payment: "**** 4231",
        fees: "$1,000",
        status: "Canceled",
    },
    {
        name: "PCR Test",
        name2: "PCR Test",
        date: "Feb 15, 2020",
        payment: "**** 4231",
        fees: "$2,300",
        status: "Not discussed",
    },
    {
        name: "PCR Test",
        name2: "PCR Test",
        date: "Feb 15, 2020",
        payment: "**** 4231",
        fees: "$3,500",
        status: "Scheduled",
    }
]